"""Parse canonical Markdown wiki cards.

The parser intentionally supports a small YAML frontmatter subset generated by
``MarkdownVault.render_card``. It is deterministic and dependency-free so it can
be used by validators, reindexers, and tests without requiring PyYAML.
"""

from __future__ import annotations

import re
import ast
from dataclasses import dataclass, field
from typing import Any


class MarkdownCardParseError(ValueError):
    pass


@dataclass
class ParsedMarkdownCard:
    id: str
    title: str
    page_type: str
    status: str = "draft"
    source_level: str = ""
    aliases: list[str] = field(default_factory=list)
    tags: list[str] = field(default_factory=list)
    sources: list[dict[str, str]] = field(default_factory=list)
    related: list[str] = field(default_factory=list)
    summary: str = ""
    sections: dict[str, str] = field(default_factory=dict)
    body: str = ""
    frontmatter: dict[str, Any] = field(default_factory=dict)


SECTION_TO_FIELD = {
    "summary": "summary",
    "problem": "problem",
    "key ideas": "key_idea",
    "key takeaways": "key_takeaways",
    "key contributions": "key_contributions",
    "method": "method",
    "methods": "method",
    "results": "results",
    "findings": "findings",
    "definition": "definition",
    "mechanism": "mechanism",
    "limitations": "limitations",
    "evidence": "evidence",
    "links": "links",
    "notes": "notes",
    "import impact": "import_impact",
    "review status": "review_status_text",
}


def parse_markdown_card(markdown: str) -> ParsedMarkdownCard:
    frontmatter, body = split_frontmatter(markdown)
    if not frontmatter:
        raise MarkdownCardParseError("Markdown card is missing frontmatter.")

    card_id = str(frontmatter.get("id") or "").strip()
    title = str(frontmatter.get("title") or "").strip()
    page_type = str(frontmatter.get("type") or frontmatter.get("page_type") or "").strip()
    if not card_id:
        raise MarkdownCardParseError("Markdown card frontmatter is missing id.")
    if not title:
        title = _title_from_body(body)
    if not title:
        raise MarkdownCardParseError("Markdown card is missing title.")
    if not page_type:
        raise MarkdownCardParseError("Markdown card frontmatter is missing type.")

    sections = parse_sections(body)
    summary = sections.get("Summary", "").strip()
    return ParsedMarkdownCard(
        id=card_id,
        title=title,
        page_type=page_type,
        status=str(frontmatter.get("status") or "draft"),
        source_level=str(frontmatter.get("source_level") or ""),
        aliases=_string_list(frontmatter.get("aliases")),
        tags=_string_list(frontmatter.get("tags")),
        sources=_source_list(frontmatter.get("sources")),
        related=_unique_strings(_string_list(frontmatter.get("related")) + wikilinks(body)),
        summary=summary,
        sections=sections,
        body=body.strip(),
        frontmatter=frontmatter,
    )


def split_frontmatter(markdown: str) -> tuple[dict[str, Any], str]:
    text = (markdown or "").replace("\r\n", "\n").replace("\r", "\n")
    if not text.startswith("---\n"):
        return {}, text
    end = text.find("\n---", 4)
    if end == -1:
        return {}, text
    raw = text[4:end].strip("\n")
    body = text[end + len("\n---"):].lstrip("\n")
    return parse_frontmatter(raw), body


def parse_frontmatter(raw: str) -> dict[str, Any]:
    data: dict[str, Any] = {}
    current_key = ""
    current_list: list[Any] | None = None
    current_item: dict[str, str] | None = None

    for line in raw.splitlines():
        if not line.strip() or line.strip().startswith("#"):
            continue
        if not line.startswith(" "):
            key, sep, value = line.partition(":")
            if not sep:
                continue
            current_key = key.strip()
            current_item = None
            value = value.strip()
            if value:
                data[current_key] = _parse_scalar(value)
                current_list = None
            else:
                current_list = []
                data[current_key] = current_list
            continue

        if current_list is None:
            continue
        stripped = line.strip()
        if stripped == "[]":
            continue
        if stripped.startswith("- "):
            item = stripped[2:].strip()
            if ":" in item and not item.startswith(("http:", "https:", "file:", "oss:", "local:")):
                key, _, value = item.partition(":")
                current_item = {key.strip(): str(_parse_scalar(value.strip()))}
                current_list.append(current_item)
            else:
                current_item = None
                current_list.append(_parse_scalar(item))
            continue
        if current_item is not None and ":" in stripped:
            key, _, value = stripped.partition(":")
            current_item[key.strip()] = str(_parse_scalar(value.strip()))

    return data


def parse_sections(body: str) -> dict[str, str]:
    sections: dict[str, str] = {}
    current = ""
    buffer: list[str] = []
    for line in (body or "").replace("\r\n", "\n").splitlines():
        match = re.match(r"^##\s+(.+?)\s*$", line)
        if match:
            if current:
                sections[current] = "\n".join(buffer).strip()
            current = match.group(1).strip()
            buffer = []
        elif current:
            buffer.append(line)
    if current:
        sections[current] = "\n".join(buffer).strip()
    return sections


def content_json_from_sections(card: ParsedMarkdownCard) -> dict[str, Any]:
    content: dict[str, Any] = {
        "schema_version": "markdown-wiki-v1",
        "markdown_status": card.status,
        "aliases": card.aliases,
        "sources": card.sources,
    }
    source_packet_ids = _unique_strings([
        str(source.get("source_packet_id") or "")
        for source in card.sources
        if source.get("source_packet_id")
    ])
    if source_packet_ids:
        content["source_packet_id"] = source_packet_ids[0]
        content["source_packet_ids"] = source_packet_ids
    for heading, value in card.sections.items():
        key = SECTION_TO_FIELD.get(heading.strip().lower()) or _field_key_from_heading(heading)
        if key == "summary":
            continue
        if key in {"key_takeaways"}:
            content[key] = _bullet_items(value)
        elif key in {"import_impact"}:
            content[key] = _structured_section(value)
        else:
            content[key] = value.strip()
    return content


def wikilinks(text: str) -> list[str]:
    seen: set[str] = set()
    values: list[str] = []
    for match in re.findall(r"\[\[([^\]]+)\]\]", text or ""):
        value = match.split("|", 1)[0].strip()
        if value and value.lower() not in seen:
            seen.add(value.lower())
            values.append(value)
    return values


def _title_from_body(body: str) -> str:
    match = re.search(r"^#\s+(.+?)\s*$", body or "", flags=re.MULTILINE)
    return match.group(1).strip() if match else ""


def _parse_scalar(value: str) -> Any:
    value = (value or "").strip()
    if value == "[]":
        return []
    if len(value) >= 2 and value[0] == value[-1] == '"':
        return value[1:-1].replace('\\"', '"')
    if value.lower() == "true":
        return True
    if value.lower() == "false":
        return False
    return value


def _string_list(value: Any) -> list[str]:
    if not isinstance(value, list):
        return []
    output: list[str] = []
    seen: set[str] = set()
    for item in value:
        if isinstance(item, dict):
            item = item.get("title") or item.get("id") or item.get("url") or ""
        text = str(item or "").strip()
        if text and text.lower() not in seen:
            seen.add(text.lower())
            output.append(text)
    return output


def _unique_strings(values: list[str]) -> list[str]:
    output: list[str] = []
    seen: set[str] = set()
    for value in values:
        text = str(value or "").strip()
        if text and text.lower() not in seen:
            seen.add(text.lower())
            output.append(text)
    return output


def _source_list(value: Any) -> list[dict[str, str]]:
    if not isinstance(value, list):
        return []
    output: list[dict[str, str]] = []
    for item in value:
        if isinstance(item, dict):
            url = str(item.get("url") or "").strip()
            if url:
                output.append({str(k): str(v) for k, v in item.items() if v not in (None, "")})
        else:
            url = str(item or "").strip()
            if url:
                output.append({"url": url})
    return output


def _bullet_items(value: str) -> list[str]:
    items = []
    for line in (value or "").splitlines():
        line = re.sub(r"^\s*[-*]\s+", "", line).strip()
        if line:
            items.append(line)
    return items


def _field_key_from_heading(heading: str) -> str:
    key = re.sub(r"[^0-9a-zA-Z\u4e00-\u9fff]+", "_", heading or "").strip("_").lower()
    return key or "notes"


def _structured_section(value: str) -> Any:
    lines = [line.strip() for line in (value or "").splitlines() if line.strip()]
    if not lines:
        return {}
    result: dict[str, Any] = {}
    matched = False
    for line in lines:
        match = re.match(r"^[-*]\s+\*\*(.+?)\*\*:\s*(.*)$", line)
        if not match:
            continue
        matched = True
        key = _field_key_from_heading(match.group(1))
        result[key] = _parse_pythonish_value(match.group(2))
    return result if matched else value.strip()


def _parse_pythonish_value(value: str) -> Any:
    text = (value or "").strip()
    if not text:
        return ""
    try:
        return ast.literal_eval(text)
    except (SyntaxError, ValueError):
        return text
